"""new_field_datetime

Revision ID: 45fbd85773d8
Revises: 54ddcabacb1a
Create Date: 2025-01-16 16:45:55.530530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45fbd85773d8'
down_revision = '54ddcabacb1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True, comment='Время создания'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
