"""init migration

Revision ID: 9bd8826d09c4
Revises: 
Create Date: 2025-01-15 16:03:05.709629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bd8826d09c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор'),
    sa.Column('amount', sa.Float(), nullable=False, comment='Сумма'),
    sa.Column('commission', sa.Float(), nullable=False, comment='Комиссия'),
    sa.Column('status', sa.String(length=12), server_default='Ожидание', nullable=False, comment='Статус'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Дата и время создания'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор'),
    sa.Column('username', sa.String(length=64), nullable=False, comment='Логин'),
    sa.Column('password_hash', sa.String(length=256), nullable=False, comment='Хэш пароля'),
    sa.Column('balance', sa.Float(), nullable=False, comment='Баланс'),
    sa.Column('commission_rate', sa.Float(), nullable=False, comment='Ставка комиссии'),
    sa.Column('webhook_url', sa.String(length=256), nullable=False, comment='URL webhook'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='Суперпользователь'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('transaction')
    # ### end Alembic commands ###
